"""empty message

Revision ID: 46f74ee348dd
Revises: 0c5769d87509
Create Date: 2023-06-12 23:02:43.327440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46f74ee348dd'
down_revision = '0c5769d87509'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('planeta_id', sa.Integer(), nullable=True),
    sa.Column('personaje_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['personaje_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['planeta_id'], ['planets.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('favoritos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favoritos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('planeta_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('personaje_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['personaje_id'], ['people.id'], name='favoritos_personaje_id_fkey'),
    sa.ForeignKeyConstraint(['planeta_id'], ['planets.id'], name='favoritos_planeta_id_fkey'),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], name='favoritos_usuario_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favoritos_pkey')
    )
    op.drop_table('favorites')
    # ### end Alembic commands ###
