"""empty message

Revision ID: 73ba4f35d884
Revises: b3cee8c1f564
Create Date: 2023-06-03 00:52:50.164502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73ba4f35d884'
down_revision = 'b3cee8c1f564'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('peopleFav',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('people_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['people_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'people_id')
    )
    op.create_table('planetsFav',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('planets_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['planets_id'], ['planets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'planets_id')
    )
    op.drop_table('favorites')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_people', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_planets', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_users', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_people'], ['people.id'], name='favorites_id_people_fkey'),
    sa.ForeignKeyConstraint(['id_planets'], ['planets.id'], name='favorites_id_planets_fkey'),
    sa.ForeignKeyConstraint(['id_users'], ['user.id'], name='favorites_id_users_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorites_pkey')
    )
    op.drop_table('planetsFav')
    op.drop_table('peopleFav')
    # ### end Alembic commands ###
